runtime: python39

env_variables:
  AUTH_TOKEN: "your_generated_auth_token"
  OPENAI_API_KEY: "your_openai_api_key"
  PERPLEXITY_API_KEY: "your_perplexity_api_key"
  GEMINI_API_KEY: "your_gemini_api_key"
  StabilityAI_API_KEY: "your_stabilityai_api_key"
  GOOGLE_API_KEY: "your_google_api_key"
  LimeWire_API_KEY: "your_limewire_api_key"
  GCP_PROJECT_ID: "your_gcp_project_id"

handlers:
  - url: /static
    static_dir: pelican-CMS/_site/content
    secure: always

  - url: /.*
    script: auto
    secure: always